name: Publish release
on: [release]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm build production artifact
      run: |
        npm ci
        npm run build
        bash -c "ls dist/id7*.zip > /github/home/fn.txt"
    - name: Upload to Release
      entrypoint: "sh"
      args: "-c upload-to-release $(cat /github/home/fn.txt)"
      uses: JasonEtco/upload-to-release@v0.1.1
